import type { Metadata } from "next";
import { Inter } from "next/font/google";
import StoreProvider from "@/app/StoreProvider";
import { wrapper } from "@/store";

import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.scss";
import Header from "@/components/organisms/Header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TEST",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Header />
          <main style={{ padding: "0 30px 30px" }}>{children}</main>
        </body>
      </html>
    </StoreProvider>
  );
}
